#!/bin/bash

# Define the directory where your files are located
files_directory="$HOME/GoogleDrive/Spirit/yoga/web"

# Define the name of the output HTML file
output_html="index.html"

# Create the HTML file
echo '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Bhakti base</title>
      <link rel="icon" type="image/x-icon" href="favicon.png">
    <style>
        body { 
            /* background-image: url("background.png"); */
            font-family: Helvetica;
        }
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .topnav {
          overflow: hidden;
          background-color: #B2A4FF;
        }

        .topnav a {
          float: left;
          display: block;
          color: #f2f2f2;
          text-align: center;
          padding: 14px 16px;
          text-decoration: none;
          font-size: 17px;
        }

        .topnav a:hover {
          background-color: #ddd;
          color: #4B0150;
        }

        .topnav a.active {
          background-color: #B2A4FF;
          color: white;
        }

        .topnav .icon {
          display: none;
        }

        @media screen and (max-width: 600px) {
          .topnav a:not(:first-child) {display: none;}
          .topnav a.icon {
            float: right;
            display: block;
          }
        }

        @media screen and (max-width: 600px) {
          .topnav.responsive {position: relative;}
          .topnav.responsive .icon {
            position: absolute;
            right: 0;
            top: 0;
          }
          .topnav.responsive a {
            float: none;
            display: block;
            text-align: left;
          }
        }        

    </style>
</head>
<body>
    <div class="topnav" id="myTopnav">
      <a href="#home" class="active">Home</a>
      <a href="#audio">Audio</a>
      <a href="#docs">Documentatie</a>
      <a href="#online">Online</a>
      <a href="https://calendar.google.com/calendar/embed?src=26474ffdbac9e6c638d4008d2b19168f5e63ae4d73b894cbc3076292af788d7f%40group.calendar.google.com&ctz=Europe%2FAmsterdam">Calender</a>
      <a href="javascript:void(0);" class="icon" onclick="myFunction()">
        <i class="fa fa-bars"></i>
      </a>
    </div>

    <h2 id="audio">Audio</h2>
    <table>
        <tr>
            <th>Categorie</th>
            <th>Link</th>
        </tr>' > "$output_html"

# Loop through files in the directory and add rows to the HTML table

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
for file in $(ls -1 ./*/*.mp3 ./*/*.mpeg|sort); do
    echo $file
    if [ -f "$file" ]; then
        category=$(basename $(dirname "$file"))
        filename=$(basename "$file")
        extention=${file##*.}
        echo "        <tr>" >> "$output_html"
        echo "            <td>$category</td>" >> "$output_html"
        echo "            <td><a href=\"$file\">$filename</a></td>" >> "$output_html"
        echo "        </tr>" >> "$output_html"
    fi
done
echo '</table> ' >> "$output_html"

    
echo '<h2 id="docs"> Documentatie</h2>
        <table>
        <tr>
            <th>Categorie</th>
            <th>Link</th>
        </tr>' >> "$output_html"

echo "        <tr>" >> "$output_html"
echo "            <td>Ekadashi</td>" >> "$output_html"
echo "            <td><a href=\"./Ekadashi.htm\">Ekadashi Betekenis Namen en Lila’s </a></td>" >> "$output_html"
echo "        </tr>" >> "$output_html"

echo "        <tr>" >> "$output_html"
echo "            <td>Sampradaaya Calender online</td>" >> "$output_html"
echo "            <td><a href=\"https://calendar.google.com/calendar/embed?src=bf4e694c5fb25a678e2bc544655a516eefd897d6aec107d334525b20aa1fef78%40group.calendar.google.com&ctz=Europe%2FAmsterdam\">Sampradaaya Kalender 2023-2024 online</a></td>" >> "$output_html"
echo "        </tr>" >> "$output_html"

echo "        <tr>" >> "$output_html"
echo "            <td>Sampradaìaya Calender ical</td>" >> "$output_html"
echo "            <td><a href=\"https://calendar.google.com/calendar/ical/bf4e694c5fb25a678e2bc544655a516eefd897d6aec107d334525b20aa1fef78%40group.calendar.google.com/public/basic.ics\">Sampradaaya Kalender 2023-2024 ical</a></td>" >> "$output_html"
echo "        </tr>" >> "$output_html"

for file in $(ls -1 ./*/*.pdf |sort); do
    echo $file
    if [ -f "$file" ]; then
        category=$(basename $(dirname "$file"))
        filename=$(basename "$file")
        extention=${file##*.}
        echo "        <tr>" >> "$output_html"
        echo "            <td>$category</td>" >> "$output_html"
        echo "            <td><a href=\"$file\">$filename</a></td>" >> "$output_html"
        echo "        </tr>" >> "$output_html"
    fi
done
IFS=$SAVEIFS

echo '</table> ' >> "$output_html"

echo '
<h2 id="online"> Online info</h2>
<table>
        <tr>
            <th>Categorie</th>
            <th>Link</th>
        </tr>
        <tr>
            <td>Info</td>
            <td><a href="https://ahc-ayurvedayoga.com/"</a>Ayurvedic Health Center Radha Shyamsundar</td>
        </tr>        
        <tr>
            <td>Info</td>
            <td><a href="https://vanipedia.org/wiki/Main_Page"</a>Vanipedia - Encyclopedia of Śrīla Prabhupāda</td>
        </tr>   
        <tr>
            <td>Info</td>
            <td><a href="https://vedabase.io/nl/"</a>Vedabase - Bhaktivedanta Vedabase</td>
        </tr>        
        <tr>
            <td>Info</td>
            <td><a href="https://bhagavata.org/"</a>Śrīmad Bhāgavatam (or the Bhāgavata Purāṇa)</td>
        </tr>   
        <tr>
            <td>Info</td>
            <td><a href="https://www.jkyog.org/swami-mukundananda"</a>Swami Mukundananda - JKYog</td>
        </tr>
        <tr>
            <td>Video</td>
            <td><a href="https://www.youtube.com/@swamimukundananda/videos"</a>Swami Mukundananda - Videos</td>
        </tr>
         <tr>
            <td>Video</td>
            <td><a href="https://www.youtube.com/@bhagavadgita4life/videos"</a>Bhagavad Gita - Videos</td>
        </tr>
        <tr>
            <td>Video</td>
            <td><a href="https://www.youtube.com/@AksharYoga/videos"</a>Akshar Yoga - Videos</td>
        </tr>
        <tr>
            <td>Video</td>
            <td><a href="https://www.youtube.com/watch?v=E53GuZ8NFQw"</a>Bhagavad-gita Chant Series - Complete Version - Anushtup Chanddah </td>
        </tr>
        <tr>
            <td>Video</td>
            <td><a href="https://www.youtube.com/playlist?list=PL8N0KCmiXH54F2EsAz7muh_gkmr-2wPC8"</a>Bhagavad Geeta recitation - By Astha Chhattani</td>
        </tr>
        
 </table>' >> "$output_html"
 
 echo '
  </body> 
  </html> ' >> "$output_html"



